### ISSUE TITLE
chore: find a logo idea

### ISSUE THREAD

**Issue by tony-go** [crossnx/includejs#15]

**Comment by tony-go** [comment]
Two ideas

![1](https://github.com/crossnx/includejs/assets/22824417/c31d2445-22d3-44be-b5c6-4220673f86d2)
![2](https://github.com/crossnx/includejs/assets/22824417/b312cec2-4ec5-420c-89cb-184b3093434c)

**Comment by tony-go** [comment]
yeah let see what @jviotti think about it :)

**Comment by jviotti** [comment]
Looks great! Feel free to start using it on the README and Doxygen

**Comment by thundron** [comment]
![#Include JS](https://github.com/crossnx/includejs/assets/5888446/0b6a901a-7862-4167-9888-9aa5c41cf5e4)
I think this is a bit more consistent with the org's logo, helps with product branding in general to have imagery consistency
